name: deployment

on:
  pull_request:
    types: 
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v1

    - name: get list of files in PR
      if: github.event.pull_request
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          echo $FILES
          
    - name: Compare names
      env:
        PAPER_NAME_MD: paper.md
        PAPER_NAME_DOCX: paper.docx
        PAPER_NAME_PDF: paper.pdf
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const diff_url = context.payload.pull_request.diff_url
          const result = await github.request.filename(diff_url)
          console.log(result.data)

