name: Docker Image CI

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: EduardBlees/Master-s-thesis/SciencePaperAnalyzer@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
