name: React-to-PR

on: 
  pull_request:
    branches: 
      - master

jobs: 
  branch_cleanup:
    runs-on: ubuntu-latest
    steps:
     - uses: jessfraz/branch-cleanup-action@master
       with: 
        token: ${{secrets.GITHUB_TOKEN}}
